@startuml
frame "Buisness context" {

node WordClock

cloud "Publicly available time delivery service" as network_time

together {
    actor Owner
    actor Developer
    Owner -[hidden]- Developer
}

Owner -> WordClock : Configuration
Owner <- WordClock : Current time
Developer -> WordClock : firmware
    
WordClock <- network_time : Current time

}
@enduml