@startuml
mainframe Building blocks - level 2

component "WordClock Firmware" as clk_fw{
    component Application {
        rectangle Behaviour
        rectangle Configuration
        rectangle Version
        rectangle Time

        component "Platform abstraction" as pal {
            interface Display
            interface PersistentStorage
            interface Network
            interface SystemTime
            interface FirmwareUpdate
        }
    }

    component Platform {
        rectangle RgbLedStripMatrix
        rectangle LedDriver
        rectangle NTP
        rectangle RTC
        rectangle NVS
        rectangle WiFi
        rectangle HttpClient
        rectangle OTA
    }
}

component "Real Time Clock" as Rtc
component "Led Matrix" as Led_matrix

Behaviour .> Configuration: use
Behaviour .> Time: use
Behaviour ..> Network: use
Behaviour ..> Display: use
Behaviour ..> Version: use
Behaviour ..> FirmwareUpdate: use
Time ..> SystemTime: use
Configuration ..> PersistentStorage: use
Version <.. FirmwareUpdate: use

Display ..> RgbLedStripMatrix: use
RgbLedStripMatrix ..> LedDriver: use
PersistentStorage ..> NVS: use
Network ..> WiFi: use
SystemTime ..> NTP: use
SystemTime ..> RTC: use
FirmwareUpdate ..> OTA: use
FirmwareUpdate ..> HttpClient: use

RTC ...> Rtc
LedDriver ..> Led_matrix

@enduml