[book]
title = "WordClock architecture documentation"
authors = ["Louis Mayencourt"]
description = "Capture the important design concept and decisions of the WordClock project"
language = "en"
multilingual = false
src = "doc/architecture/"

[build]
build-dir = "target/architecture"