[package]
authors = ["Louis Mayencourt <louis.mayencourt@gmail.com>"]
name = "xtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
xshell = "0.2.3"