[alias]
xtask = 'run -p xtask --'
xcheck = 'run -p xtask -- check'
xbuild = 'run -p xtask -- build'
xclean = 'run -p xtask -- clean'
xflash = 'run -p xtask -- flash'
xdoc = 'run -p xtask -- doc'
uml = 'run -p xtask -- uml'
generate_ota = 'run -p xtask -- generate_ota'