[package]
name = "application"
version = "0.1.0"
edition = "2021"
authors = ["louismayencourt <louis.mayencourt@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.0"
regex = "1.8.1"